services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:latest
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=financeApp
    ports: 
      - 5432:5432